language: node_js

node_js:
  - "8"

install:
 - "yarn install --no-lockfile"

script:
  - "yarn test:reactTestingLibrary --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
